services:
  postgres:
    image: postgres:18
    container_name: banking-postgres
    environment:
      POSTGRES_DB: bankingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - banking_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bankingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  banking-api:
    build: .
    container_name: banking-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  banking_postgres_data: