POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Marina",
  "lastName": "Likhareva",
  "dateOfBirth": "1995-01-10",
  "email": "marina@test.de",
  "password": "MeinPasswort123"
}

### Create account
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "userId": "e23d3bcc-c59a-4923-ae9e-cadc944efe55",
  "accountType": "CHECKING"
}